version: "3"
services:
  # Database layer
  my_database:
    image: mysql/mysql-server:5.6
    container_name: my_database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  # Webserver layer
  my_webserver:
    build: .
    container_name: my_webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/project
    links:
      - my_database
